config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  get "/sessions/new", to: "sessions#new"
  post "/sessions/create", to: "sessions#create"
  delete "/signout", to: "sessions#destroy"

  get "/users/:id/delete", to: "users#delete"
  get "/employees/:id/delete", to: "employees#delete"
  get "/issues/:id/delete", to: "issues#delete"

  # Sorting Issues
  get "/issues/by_effort", to: "issues#effort_sort"
 
  resources :users do
    resources :issues, only: [:index, :new, :edit, :show]
  end

  #resources :users
  resources :issues
  resources :employees

  resources :issues do
    resources :comments
  end

  get '/auth/github/callback', to: 'sessions#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
    validates :name, :department, presence: true
    validates :name, uniqueness: true

    has_many :issues, inverse_of: :employee
    has_many :users, :through => :issues
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    before_action :require_admin

  def index
    @employees = Employee.all
  end 

  def show
    @employee = Employee.find(params[:id])
  end

  def new
  # only Admin can create new employee when logged in
  # logged-in users will not have access to new and create employee methods
    if current_user && current_user.role != "Admin"
      redirect_to user_path(current_user)
    end
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      # Admin is redirected to employees index after creating a employee.
      redirect_to employees_path
    else
      render :new
    end
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.update(employee_params)
      redirect_to @employee, notice: 'employee was successfully updated.'
    else
      render :edit
    end
  end

  def delete
    #byebug
    @employee = Employee.find(params[:id])
  end

  def destroy
    #byebug
    @employee = Employee.find(params[:id])
    @employee.delete

    #current_employee should be Admin at this point since only Admin should have access to destroy method
    redirect_to employees_path(current_user)   
  end

  private
    def require_admin
    #byebug
      redirect_to user_path(current_user) unless current_user.role === "Admin"
    end

    def employee_params
      params.require(:employee).permit(
      :name,
      :department
      )
    end

end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>

  <% if @employee.errors.any? %>
    <div id="error_explanation" class="field_with_errors">
      <h2>There were some errors:</h2>
        <ul>
          <% @employee.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    </div>
  <% end %>

    <div class="form-group<%= ' field_with_errors' if @employee.errors[:name].any? %>">
      <%= f.label :name, "Name" %><br>
      <%= f.text_field :name, class: "form-control" %>
    </div>
   
    <div class="form-group<%= ' field_with_errors' if @employee.errors[:department].any? %>">
      <%= f.label :department, "Department" %><br>
      <%= f.text_field :department, class: "form-control" %>
    </div>
  
    <div class="actions">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  <% end %>

app/views/employees/delete.html.erb
<form>
Employee Id: <input type="text" value="<%= @employee.id %>" readonly=true><br>

Name: <input type="text" value="<%= @employee.name %>" readonly=true><br>

Department:<input type="text" value="<%= @employee.department %>" readonly=true><br>

</form>

<%= form_tag employee_path, method: :delete, data: { confirm: 'Are you sure?' } do %>
   <input type=submit value='Delete User'>    
<% end %>

app/views/employees/edit.html.erb
<h1>Edit employee</h1>

<%= render 'form' %>

app/views/employees/index.html.erb
<h1>Listing Employees</h1>

<% if @employees.length == 0 %>
    <p> There are no employees at this time. <p>
<% else %>

    <table class="table table-bordered table-responsive table-sm table-hover">

    <thead>
        <tr>
        <th colspan="3"></th>
        </tr>
    </thead>
        
    <tbody>
        <tr> 
        <td><strong>ID</strong></td>
        <td><strong>Name</strong></td>
        <td><strong>Department</strong></td>
        <td><strong>Delete?</td>
        </tr>

        <% @employees.each do |employee| %>
          <tr>
            <td><a href="employees/<%=employee.id%>/edit"><%= employee.id %></a>
            <td><%= employee.name %></td>
            <td><%= employee.department %></td>
            <% if current_user.role === "Admin" %>
                <td><a href="/employees/<%=employee.id%>/delete">X</a></td>
            <% else %>
                <td></td>             
            <% end %>    
          </tr>
        <% end %>
    </tbody>
    </table>

  <% end%>
<br>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

app/views/employees/show.html.erb
<label>Name: </label>
<p><%= @employee.name %></p>

<label>Department: </label>
<p><%= @employee.department %></p>

  
<label>Created at: </label>
<p><%= @employee.created_at %></p>
<label>Updated at: </label>
<p><%= @employee.updated_at %></p>

<p><%= link_to 'Edit', edit_employee_path(@employee) %></p>