config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  get "/sessions/new", to: "sessions#new"
  post "/sessions/create", to: "sessions#create"
  delete "/signout", to: "sessions#destroy"

  get "/users/:id/delete", to: "users#delete"
  get "/employees/:id/delete", to: "employees#delete"
  get "/issues/:id/delete", to: "issues#delete"

  # Sorting Issues
  get "/issues/by_effort", to: "issues#effort_sort"
 
  resources :users do
    resources :issues, only: [:index, :new, :edit, :show]
  end

  #resources :users
  resources :issues
  resources :employees

  resources :issues do
    resources :comments
  end

  get '/auth/github/callback', to: 'sessions#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/issue.rb
class Issue < ApplicationRecord
  validates :title, :created, presence: true
  validates :effort, numericality: {only_integer: true, allow_nil: true}

  belongs_to :user
  belongs_to :employee
  validates :user, :employee, presence: true

  has_many :comments, inverse_of: :issue
  # has_many :users, :through => :comments

  scope :order_by_latest, -> { order(created: :desc) }
  scope :order_by_effort, -> { order(effort: :asc) }
    
  # scope :created_before, ->(time) { where("created -  <= ?", time) }


end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :exclude_guest, only: [:new, :create, :edit, :update, :delete, :destroy]

  def index
    if params[:user_id]
      @issues = User.find(params[:user_id]).issues.order_by_latest
      # respond_to do |format|
      #   format.html { render :index }
      #   format.json { render json: @issues, status: 200 }
      # end
      render json: @issues, layout: false, status: 200
    else
      @issues = Issue.all.order_by_latest
      respond_to do |format|
        format.html { render :index }
        format.json { render json: @issues, status: 200 }
      end
    end
  end 
    
  #sort index output by effort
  def effort_sort
    @issues = Issue.all.order_by_effort  
    render :index  
  end

  def show
    @issue = Issue.find(params[:id])
    # @comments = @issue.comments
    @comment = Comment.new

    respond_to do |format|
      format.html { render :show }
      format.json { render json: @issue, status: 200 }
    end
  end
    
  def new
    @issue = Issue.new
  end
    
  def create
    @issue = Issue.new(issue_params)
    if @issue.save
      redirect_to issues_path
    else
      render :new
    end
  end

  def edit
    @issue = Issue.find(params[:id])
  end
  
  def update
    @issue = Issue.find(params[:id])
    if @issue.update(issue_params)
      redirect_to issues_path(current_user), notice: 'Issue was successfully updated.'
    else
      render :edit
    end
  end
 
  def delete
    @issue = Issue.find(params[:id])
  end
    
  def destroy
    @issue = Issue.find(params[:id])
    @issue.delete
    
    #current_employee should be Admin at this point since only Admin should have access to destroy method
    redirect_to issues_path(current_user)   
  end
    
  private
    def require_admin
      redirect_to user_path(current_user) unless current_user.role === "Admin"
    end
  
    def exclude_guest
      redirect_to issues_path(current_user) if current_user.role.downcase === "guest"
    end


    def issue_params
      params.require(:issue).permit(
      :title,
      :status,
      :owner,
      :created,
      :effort,
      :completion_date,
      :employee_id,
      :user_id
      )
    end

end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= form_for @issue do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation" class="field_with_errors">
    <h2>There were some errors:</h2>
    <ul>
      <% @issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    </div>
  <% end %>

  <div class="form-group<%= ' field_with_errors' if @issue.errors[:title].any? %>">
    <%= f.label :title, "Title (Required)" %><br>
    <%= f.text_field :title, class: "form-control", placeholder: "Required" %>
  </div>

  <div class="form-group">
    <%= f.label :status, "Status*" %><br>
    <%= f.text_field :status, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :owner, "Owner" %><br>
    <%= f.collection_select :owner, User.all.L2_L3_only, :name, :name, include_blank: 'Choose an Owner', class: "form-control" %>
  </div>

  <div class="form-group<%= ' field_with_errors' if @issue.errors[:created].any? %>">
    <%= f.label :created, "Created (Required)" %><br>
    <% if @issue.created.nil? %>
      <%= f.text_field :created, class: "form-control", value:Time.now %>
    <% else %>
      <%= f.text_field :created, class: "form-control" %>
    <% end %>
  </div>

  <div class="form-group<%= ' field_with_errors' if @issue.errors[:effort].any? %>">
    <%= f.label :effort, "Effort (hrs)" %><br>
    <%= f.text_field :effort, class: "form-control" %>
  </div>

  <div class="form-group<%= ' field_with_errors' if @issue.errors[:completion_date].any? %>">
    <%= f.label :completion_date, "Completion Date" %><br>
    <%= f.text_field :completion_date, class: "form-control" %>
  </div>

  <div class="form-group<%= ' field_with_errors' if @issue.errors[:employee].any? %>">
    <%= f.label :employee_id, "Employee/Caller (Required)" %><br>
    <%= f.collection_select :employee_id, Employee.all, :id, :name, include_blank: 'Choose an Employee', class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :user_id, "User ID" %><br>
    <%= f.text_field :user_id, value: current_user.id, class: "form-control" %>
  </div>

  <%= f.submit %>
<% end %>

<p>* New - service desk has received the incident but has not assigned it to an agent.</p>
<p> Assigned - incident has been assigned to an individual service desk agent.</p>
<p> In-Progress - incident has been assigned to an agent but has not been resolved. The agent is actively working with the user to diagnose and resolve the incident.</p>
<p> On-Hold - incident requires some information or response from the user or from a third party. SLA response deadlines are not exceeded while waiting for a response from the user or vendor.</p>
<p> Resolved - service desk has confirmed that the incident is resolved and that the user’s service has restored to the SLA levels.</p>
<p> Closed - incident is resolved and that no further actions can be taken.</p>

app/views/issues/delete.html.erb
<form>
Issue Id: <input type="text" value="<%= @issue.id %>" readonly=true><br>

Title: <input type="text" value="<%= @issue.title %>" readonly=true><br>

Status: <input type="text" value="<%= @issue.status %>" readonly=true><br>

Owner: <input type="text" value="<%= @issue.owner %>" readonly=true><br>

Created: <input type="text" value="<%= @issue.created %>" readonly=true><br>

Completion: <input type="text" value="<%= @issue.completion_date %>" readonly=true><br>

Created by: <input type="text" value="<%= @issue.user.name %>" readonly=true><br>

Escalated by:<input type="text" value="<%= @issue.employee.name %>" readonly=true><br>

Department: <input type="text" value="<%= @issue.employee.department %>" readonly=true><br>

</form>

<%= form_tag issue_path, method: :delete, data: { confirm: 'Are you sure?' } do %>
   <input type=submit value='Delete Issue'>    
<% end %>

app/views/issues/edit.html.erb
<h1>Edit Issue</h1>

<%= render 'form' %>

app/views/issues/index.html.erb
<h1>Listing Issues</h1>

<% if @issues.length == 0 %>
    <p> There are no issues at this time. <p>
<% else %>

    <p id="domReadyCheck">Not loaded yet.</p>

    <table id="issuesTable" class="table table-bordered table-responsive table-sm table-hover">
    <thead>
        <tr>
        <td><strong>ID</strong></td>
        <td id="sortTitle"><strong><a href="#">Title</strong></td>
        <td><strong>Status</strong></td>
        <td><strong>Owner</strong></td>
        <td><strong>Created</td>
        <td><strong><a href="/issues/by_effort">Effort</td>
        <td><strong>Completion Date</td>
        <td><strong>User ID</td>
        <td><strong>Employee Name</td>        
        <td><strong>Department</td>        
        <td><strong>Delete?</td>

        </tr>
    </thead>
        
    <tbody id="issuesTableBody" >
        <% @issues.each do |issue| %>
          <tr>
            <td><a href="issues/<%=issue.id%>/edit"><%= issue.id %></a>
            <td><a href="issues/<%=issue.id%>"><%= issue.title %></td>
            <td><%= issue.status %></td>
            <td><%= issue.owner %></td>
            <td><%= issue.created %></td>
            <td><%= issue.effort %></td>
            <td><%= issue.completion_date %></td>
            <td><%= issue.user.name %></td>
            <td><%= issue.employee.name %></td>
            <td><%= issue.employee.department %></td>
            <td><a href="/issues/<%=issue.id%>/delete">X</a></td> 
          </tr>
        <% end %>
    </tbody>
    </table>

  <% end%>
<br>

app/views/issues/new.html.erb
<h1>New Issue</h1>

<%= render 'form' %>

app/views/issues/show.html.erb
<h1>Show Issue</h1>

<div class="show_page">
  <a href="/issues/<%=@issue.id%>/edit" class="btn btn-warning" role="button">Update Issue</a>
  <a href="#" id="js-next" class="btn btn-info" data-id="<%=@issue.id%>">Next Issue</a>
</div>

<div class="show_page">
  <p id="issueId">Issue ID: <%= @issue.id %></p>
  <p id="issueTitle">Title: <%= @issue.title %></p>
  <p id="issueStatus">Status: <%= @issue.status %></p>
  <p id="issueOwner">Owner: <%= @issue.owner %></p>
  <p id="issueCreated">Created: <%= @issue.created %></p>
  <p id="issueEffort">Effort (hrs): <%= @issue.effort %></p>
  <p id="issueCompletion">Completion Date: <%= @issue.completion_date %></p>
  <p id="issueEmployee">Employee/Caller: <%= @issue.employee.name %></p>
  <p id="issueUser">UserID: <%= @issue.user.name %></p>
</div>

<h3><%= link_to "Comments/Notes:", issue_comments_path(@issue), id: "load_comments" %></h3>

<p id="commentMessage"></p>

<div class="listOfComments">
  <table class="table table-bordered table-responsive table-sm table-hover">
    <thead>
      <tr>
      <td><strong>Comment ID</strong></td>
      <td><strong>Comment</strong></td>
      <td><strong>User</strong></td>
      <td><strong>Created at</strong></td>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>

</div>

<label>Add Comments: </label> 
<%= form_for([@issue, @comment]) do |f| %>
  <%= f.text_area :comment %>
  <%= f.text_field :user_id, type: "hidden", value: current_user.id %>
  <%= f.text_field :issue_id, type: "hidden", value: @issue.id %>
  <p><%= f.submit 'Submit', data: { disable_with: false } %></p>

<% end %>