config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  get "/sessions/new", to: "sessions#new"
  post "/sessions/create", to: "sessions#create"
  delete "/signout", to: "sessions#destroy"

  get "/users/:id/delete", to: "users#delete"
  get "/employees/:id/delete", to: "employees#delete"
  get "/issues/:id/delete", to: "issues#delete"

  # Sorting Issues
  get "/issues/by_effort", to: "issues#effort_sort"
 
  resources :users do
    resources :issues, only: [:index, :new, :edit, :show]
  end

  #resources :users
  resources :issues
  resources :employees

  resources :issues do
    resources :comments
  end

  get '/auth/github/callback', to: 'sessions#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsJavascriptCrudIssueManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="turbolinks-visit-control" content="reload">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> 

  </head>

  <body>
    <div class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <% if !current_user %>
            <a class="navbar-brand" href="<%= root_url %>"/>Home</a>
          <% end %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <% if current_user %>
              <li><%= link_to "Hello, #{current_user.name} (#{current_user.role})!", user_path(current_user.id) %></li>
              <% if current_user.role == "Admin" %>
                <li><%= link_to 'All Users', users_path %></li>
                <li><%= link_to 'Create New User', new_user_path %></li>
                <li><%= link_to 'All Employees', employees_path %></li>
                <li><%= link_to 'Create New Employee', new_employee_path %></li>
              <% end %>

              <% if current_user.role.downcase != "guest" %>
                <li><%= link_to "New Issue", new_user_issue_path(current_user.id) %></li>
                <li id="userIssueList" ><%= link_to "My Issue List", user_issues_path(current_user.id) %></li>
              <% end %>
              <li><%= link_to "All Issues", issues_path %></li>
              <li><%= link_to "Log Out", signout_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign Up", new_user_path %></li>
              <li><%= link_to "Sign In", sessions_new_path %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container-fluid">
      <div class="show_page">
        <%= image_tag("rf_company.png", size: "150x126", alt:"Company logo") %> 
        <span style='font-size: 24pt;' >Rails Service Desk Issue Manager</span>
      </div>

      <div>

        <%= yield %>

      </div>

      <footer class="branding">
        <small>&copy; 2018 <strong>RailsJavascriptCrudIssueManager by Richard Fenix</strong></small>
      </footer>

    </div>

  </body>
</html>